import type { Vehicle, Booking, Customer, Review, RevenueData, FleetStatus, CategoryRevenue } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: 1,
    name: "Tesla Model 3",
    category: "Electric",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop",
    price: 329,
    status: "available",
    seats: 5,
    transmission: "Automatic",
    rating: 4.9,
    reviews: 156,
    year: 2024,
  },
  {
    id: 2,
    name: "BMW X5",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop",
    price: 549,
    status: "rented",
    seats: 7,
    transmission: "Automatic",
    rating: 4.8,
    reviews: 128,
    year: 2024,
  },
  {
    id: 3,
    name: "Mercedes-Benz C300",
    category: "Luxury",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop",
    price: 475,
    status: "available",
    seats: 5,
    transmission: "Automatic",
    rating: 4.9,
    reviews: 98,
    year: 2024,
  },
  {
    id: 4,
    name: "Audi Q7",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop",
    price: 585,
    status: "available",
    seats: 7,
    transmission: "Automatic",
    rating: 4.7,
    reviews: 87,
    year: 2024,
  },
  {
    id: 5,
    name: "Toyota Camry",
    category: "Sedan",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop",
    price: 239,
    status: "available",
    seats: 5,
    transmission: "Automatic",
    rating: 4.6,
    reviews: 234,
    year: 2024,
  },
  {
    id: 6,
    name: "Porsche 911",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop",
    price: 1099,
    status: "available",
    seats: 2,
    transmission: "Automatic",
    rating: 5.0,
    reviews: 45,
    year: 2024,
  },
  {
    id: 7,
    name: "Range Rover Sport",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&auto=format&fit=crop",
    price: 729,
    status: "maintenance",
    seats: 5,
    transmission: "Automatic",
    rating: 4.8,
    reviews: 76,
    year: 2024,
  },
  {
    id: 8,
    name: "Nissan Patrol",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1568844293986-8c8f0c31d2a5?w=800&auto=format&fit=crop",
    price: 449,
    status: "available",
    seats: 8,
    transmission: "Automatic",
    rating: 4.5,
    reviews: 189,
    year: 2024,
  },
  {
    id: 9,
    name: "Ford Mustang GT",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1584345604476-8ec5f82d661f?w=800&auto=format&fit=crop",
    price: 659,
    status: "rented",
    seats: 4,
    transmission: "Manual",
    rating: 4.9,
    reviews: 112,
    year: 2024,
  },
  {
    id: 10,
    name: "Lexus ES",
    category: "Luxury",
    image: "https://images.unsplash.com/photo-1617704548623-340376564e68?w=800&auto=format&fit=crop",
    price: 399,
    status: "available",
    seats: 5,
    transmission: "Automatic",
    rating: 4.6,
    reviews: 67,
    year: 2024,
  },
  {
    id: 11,
    name: "Chevrolet Tahoe",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop",
    price: 619,
    status: "available",
    seats: 8,
    transmission: "Automatic",
    rating: 4.7,
    reviews: 54,
    year: 2024,
  },
  {
    id: 12,
    name: "Lamborghini Huracán",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format&fit=crop",
    price: 2499,
    status: "available",
    seats: 2,
    transmission: "Automatic",
    rating: 4.8,
    reviews: 89,
    year: 2024,
  },
];

export const bookings: Booking[] = [
  {
    id: "BK-1001",
    customer: "Ahmed Al Maktoum",
    customerAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
    vehicle: "BMW X5 2024",
    startDate: "Feb 5, 2024",
    endDate: "Feb 8, 2024",
    total: 1647,
    status: "active",
  },
  {
    id: "BK-1002",
    customer: "Fatima Al Nahyan",
    customerAvatar: "https://randomuser.me/api/portraits/women/45.jpg",
    vehicle: "Tesla Model 3",
    startDate: "Feb 6, 2024",
    endDate: "Feb 10, 2024",
    total: 1316,
    status: "pending",
  },
  {
    id: "BK-1003",
    customer: "Rajesh Sharma",
    customerAvatar: "https://randomuser.me/api/portraits/men/36.jpg",
    vehicle: "Mercedes-Benz C300",
    startDate: "Feb 4, 2024",
    endDate: "Feb 5, 2024",
    total: 475,
    status: "completed",
  },
  {
    id: "BK-1004",
    customer: "Aisha Khalid",
    customerAvatar: "https://randomuser.me/api/portraits/women/57.jpg",
    vehicle: "Audi Q7 2024",
    startDate: "Feb 7, 2024",
    endDate: "Feb 12, 2024",
    total: 2925,
    status: "upcoming",
  },
  {
    id: "BK-1005",
    customer: "Vikram Patel",
    customerAvatar: "https://randomuser.me/api/portraits/men/47.jpg",
    vehicle: "Toyota Camry",
    startDate: "Feb 3, 2024",
    endDate: "Feb 4, 2024",
    total: 239,
    status: "completed",
  },
  {
    id: "BK-1006",
    customer: "Noura Al Qasimi",
    customerAvatar: "https://randomuser.me/api/portraits/women/62.jpg",
    vehicle: "Porsche 911",
    startDate: "Feb 8, 2024",
    endDate: "Feb 9, 2024",
    total: 1099,
    status: "upcoming",
  },
  {
    id: "BK-1007",
    customer: "Mohammed Al Farsi",
    customerAvatar: "https://randomuser.me/api/portraits/men/52.jpg",
    vehicle: "Nissan Patrol",
    startDate: "Feb 2, 2024",
    endDate: "Feb 3, 2024",
    total: 449,
    status: "completed",
  },
  {
    id: "BK-1008",
    customer: "Priya Nair",
    customerAvatar: "https://randomuser.me/api/portraits/women/68.jpg",
    vehicle: "Ford Mustang GT",
    startDate: "Feb 5, 2024",
    endDate: "Feb 7, 2024",
    total: 1318,
    status: "active",
  },
  {
    id: "BK-1009",
    customer: "Sultan Al Rashid",
    customerAvatar: "https://randomuser.me/api/portraits/men/64.jpg",
    vehicle: "Lexus ES",
    startDate: "Feb 9, 2024",
    endDate: "Feb 11, 2024",
    total: 798,
    status: "upcoming",
  },
  {
    id: "BK-1010",
    customer: "Deepika Menon",
    customerAvatar: "https://randomuser.me/api/portraits/women/78.jpg",
    vehicle: "Chevrolet Tahoe",
    startDate: "Feb 1, 2024",
    endDate: "Feb 3, 2024",
    total: 1238,
    status: "completed",
  },
  {
    id: "BK-1011",
    customer: "Khalid bin Zayed",
    customerAvatar: "https://randomuser.me/api/portraits/men/73.jpg",
    vehicle: "Lamborghini Huracán",
    startDate: "Feb 10, 2024",
    endDate: "Feb 12, 2024",
    total: 4998,
    status: "upcoming",
  },
  {
    id: "BK-1012",
    customer: "Ananya Krishnan",
    customerAvatar: "https://randomuser.me/api/portraits/women/85.jpg",
    vehicle: "Range Rover Sport",
    startDate: "Jan 28, 2024",
    endDate: "Jan 30, 2024",
    total: 1458,
    status: "completed",
  },
  {
    id: "BK-1013",
    customer: "Hamad Al Suwaidi",
    customerAvatar: "https://randomuser.me/api/portraits/men/81.jpg",
    vehicle: "Tesla Model 3",
    startDate: "Feb 11, 2024",
    endDate: "Feb 14, 2024",
    total: 987,
    status: "pending",
  },
  {
    id: "BK-1014",
    customer: "Mariam Al Shamsi",
    customerAvatar: "https://randomuser.me/api/portraits/women/89.jpg",
    vehicle: "BMW X5 2024",
    startDate: "Feb 12, 2024",
    endDate: "Feb 15, 2024",
    total: 1647,
    status: "upcoming",
  },
  {
    id: "BK-1015",
    customer: "Arjun Reddy",
    customerAvatar: "https://randomuser.me/api/portraits/men/91.jpg",
    vehicle: "Audi Q7",
    startDate: "Jan 25, 2024",
    endDate: "Jan 27, 2024",
    total: 1170,
    status: "completed",
  },
];

export const customers: Customer[] = [
  {
    id: 1,
    name: "Ahmed Al Maktoum",
    email: "ahmed.maktoum@email.ae",
    phone: "+971 50 123 4567",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    totalBookings: 12,
    totalSpent: 16820,
    rating: 4.9,
    isVIP: true,
    joinedDate: "Mar 2022",
  },
  {
    id: 2,
    name: "Fatima Al Nahyan",
    email: "fatima.nahyan@email.ae",
    phone: "+971 55 234 5678",
    avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    totalBookings: 5,
    totalSpent: 6950,
    rating: 5.0,
    isVIP: false,
    joinedDate: "Jan 2023",
  },
  {
    id: 3,
    name: "Rajesh Sharma",
    email: "rajesh.sharma@email.com",
    phone: "+971 52 345 6789",
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
    totalBookings: 8,
    totalSpent: 8600,
    rating: 4.7,
    isVIP: false,
    joinedDate: "Jun 2023",
  },
  {
    id: 4,
    name: "Aisha Khalid",
    email: "aisha.khalid@email.ae",
    phone: "+971 56 456 7890",
    avatar: "https://randomuser.me/api/portraits/women/57.jpg",
    totalBookings: 15,
    totalSpent: 20840,
    rating: 4.8,
    isVIP: true,
    joinedDate: "Feb 2022",
  },
  {
    id: 5,
    name: "Vikram Patel",
    email: "vikram.patel@email.com",
    phone: "+971 54 567 8901",
    avatar: "https://randomuser.me/api/portraits/men/47.jpg",
    totalBookings: 3,
    totalSpent: 3270,
    rating: 4.5,
    isVIP: false,
    joinedDate: "Dec 2023",
  },
  {
    id: 6,
    name: "Noura Al Qasimi",
    email: "noura.qasimi@email.ae",
    phone: "+971 58 678 9012",
    avatar: "https://randomuser.me/api/portraits/women/62.jpg",
    totalBookings: 9,
    totalSpent: 12690,
    rating: 4.9,
    isVIP: true,
    joinedDate: "Apr 2022",
  },
  {
    id: 7,
    name: "Mohammed Al Farsi",
    email: "mohammed.farsi@email.ae",
    phone: "+971 50 789 0123",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    totalBookings: 4,
    totalSpent: 4120,
    rating: 4.6,
    isVIP: false,
    joinedDate: "Sep 2023",
  },
  {
    id: 8,
    name: "Priya Nair",
    email: "priya.nair@email.com",
    phone: "+971 55 890 1234",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    totalBookings: 7,
    totalSpent: 10220,
    rating: 4.8,
    isVIP: false,
    joinedDate: "Jul 2023",
  },
  {
    id: 9,
    name: "Sultan Al Rashid",
    email: "sultan.rashid@email.ae",
    phone: "+971 52 901 2345",
    avatar: "https://randomuser.me/api/portraits/men/64.jpg",
    totalBookings: 11,
    totalSpent: 15560,
    rating: 4.7,
    isVIP: true,
    joinedDate: "May 2022",
  },
  {
    id: 10,
    name: "Deepika Menon",
    email: "deepika.menon@email.com",
    phone: "+971 56 012 3456",
    avatar: "https://randomuser.me/api/portraits/women/78.jpg",
    totalBookings: 6,
    totalSpent: 7720,
    rating: 5.0,
    isVIP: false,
    joinedDate: "Oct 2023",
  },
];

export const reviews: Review[] = [
  {
    id: 1,
    customer: "Fatima Al Nahyan",
    avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    vehicle: "Tesla Model 3",
    rating: 5,
    date: "Feb 4, 2024",
    comment: "Amazing experience! The Tesla was spotless and fully charged. Pickup at Dubai Mall was quick and easy. Will definitely rent from Ezhire Cars again!",
  },
  {
    id: 2,
    customer: "Ahmed Al Maktoum",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    vehicle: "BMW X5 2024",
    rating: 5,
    date: "Feb 3, 2024",
    comment: "Perfect SUV for our family trip to Abu Dhabi. Spacious, comfortable, and drove like a dream. Highly recommend Ezhire Cars!",
  },
  {
    id: 3,
    customer: "Rajesh Sharma",
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
    vehicle: "Mercedes-Benz C300",
    rating: 4,
    date: "Feb 2, 2024",
    comment: "Great luxury car at a reasonable price. Delivery to my hotel in Marina was perfect. Only minor delay, but otherwise excellent service.",
  },
  {
    id: 4,
    customer: "Aisha Khalid",
    avatar: "https://randomuser.me/api/portraits/women/57.jpg",
    vehicle: "Porsche 911",
    rating: 5,
    date: "Jan 30, 2024",
    comment: "Dream car experience! The Porsche was incredible for driving around Palm Jumeirah. Made our anniversary weekend unforgettable!",
  },
  {
    id: 5,
    customer: "Mohammed Al Farsi",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    vehicle: "Nissan Patrol",
    rating: 4,
    date: "Jan 28, 2024",
    comment: "Perfect for desert safari! Reliable and powerful. Great value for money. Would rent again for sure.",
  },
  {
    id: 6,
    customer: "Noura Al Qasimi",
    avatar: "https://randomuser.me/api/portraits/women/62.jpg",
    vehicle: "Audi Q7",
    rating: 5,
    date: "Jan 25, 2024",
    comment: "The Audi Q7 exceeded my expectations. Luxurious interior, smooth ride, and the team was incredibly helpful with delivery to JBR.",
  },
  {
    id: 7,
    customer: "Vikram Patel",
    avatar: "https://randomuser.me/api/portraits/men/47.jpg",
    vehicle: "Toyota Camry",
    rating: 5,
    date: "Jan 22, 2024",
    comment: "Simple, clean, and reliable. Exactly what I needed for my business meetings in DIFC. Competitive pricing too!",
  },
  {
    id: 8,
    customer: "Priya Nair",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    vehicle: "Ford Mustang GT",
    rating: 5,
    date: "Jan 20, 2024",
    comment: "What a thrill! The Mustang was in perfect condition and so fun to drive on Sheikh Zayed Road. Made my weekend epic!",
  },
];

export const revenueData: RevenueData[] = [
  { month: "Mar", revenue: 119200 },
  { month: "Apr", revenue: 106400 },
  { month: "May", revenue: 129600 },
  { month: "Jun", revenue: 153800 },
  { month: "Jul", revenue: 177400 },
  { month: "Aug", revenue: 191800 },
  { month: "Sep", revenue: 167900 },
  { month: "Oct", revenue: 143200 },
  { month: "Nov", revenue: 155700 },
  { month: "Dec", revenue: 205400 },
  { month: "Jan", revenue: 158900 },
  { month: "Feb", revenue: 178500 },
];

export const fleetStatus: FleetStatus[] = [
  { name: "Available", value: 24, color: "#22C55E" },
  { name: "Rented", value: 4, color: "#FF4500" },
  { name: "Maintenance", value: 2, color: "#F59E0B" },
];

export const revenueByCategory: CategoryRevenue[] = [
  { name: "SUV", value: 42, amount: 642800 },
  { name: "Luxury", value: 28, amount: 425200 },
  { name: "Electric", value: 15, amount: 227900 },
  { name: "Sports", value: 10, amount: 152000 },
  { name: "Sedan", value: 5, amount: 76000 },
];

export const bookingTrends = [
  { day: "Mon", bookings: 12 },
  { day: "Tue", bookings: 19 },
  { day: "Wed", bookings: 15 },
  { day: "Thu", bookings: 22 },
  { day: "Fri", bookings: 28 },
  { day: "Sat", bookings: 35 },
  { day: "Sun", bookings: 25 },
];

export const pickupTimes = [
  { time: "6AM-9AM", count: 45 },
  { time: "9AM-12PM", count: 78 },
  { time: "12PM-3PM", count: 56 },
  { time: "3PM-6PM", count: 89 },
  { time: "6PM-9PM", count: 34 },
];

export const vehicleUtilization = [
  { vehicle: "Tesla Model 3", utilization: 92 },
  { vehicle: "BMW X5", utilization: 88 },
  { vehicle: "Mercedes C300", utilization: 85 },
  { vehicle: "Porsche 911", utilization: 78 },
  { vehicle: "Audi Q7", utilization: 75 },
  { vehicle: "Nissan Patrol", utilization: 72 },
];

export const dashboardStats = {
  totalRevenue: 178500,
  revenueChange: 12.5,
  totalBookings: 156,
  bookingsChange: 8.2,
  availableVehicles: 24,
  totalVehicles: 30,
  totalCustomers: 1248,
  customersChange: 15.3,
};

export const topVehicles = [
  { name: "Tesla Model 3", bookings: 45, revenue: 45630 },
  { name: "BMW X5 2024", bookings: 38, revenue: 41220 },
  { name: "Mercedes C300", bookings: 32, revenue: 36080 },
];
